### ISSUE TITLE
 Class ShoppingCartServiceImpl must  be  created

### ISSUE THREAD

**Issue by VitRod** [VitRod/Shopping-cart-site-spring-boot#49]
the class ShoppingCartServiceImpl  must implements  interface ShoppingCartService

**Comment by vit-test-github** [comment]
The work on the implementaion of Service continues

**Comment by VitRod** [comment]
Methods addProduct,  removeProduct, getProductsInCart,  getTotal are added

**Comment by VitRod** [comment]
the  task is finished
