### ISSUE TITLE
To make configuration file  for Spring Security

### ISSUE THREAD

**Issue by VitRod** [VitRod/Shopping-cart-site-spring-boot#50]
In this  class must be  present business logic  of Spring Security configuration

**Comment by vit-test-github** [comment]
Spring Security is configured in proprties and the work with the class Config is in process

**Comment by VitRod** [comment]
To the  configuration class I added method  passwordEncoder() to encode the  password of the  application with Spring Security

**Comment by VitRod** [comment]
added method configure  that  specifies role Admin(allows  to access  admin), role user (allows  to access  user),
specifies pages  /, /home, /about, /registration, /error. Every other page needs authentication.
also specified custom 403 access denied handler.

**Comment by VitRod** [comment]
Configured variables  with annotations  Value  to spring configurations ib properties  file

**Comment by VitRod** [comment]
task is  finished
